// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfYJ9JDBCf0kqk5J0MH2Sy1rS7IRS4Zk',
    appId: '1:728200174850:web:686e9a35739c496492f61b',
    messagingSenderId: '728200174850',
    projectId: 'manage-user-1477b',
    authDomain: 'manage-user-1477b.firebaseapp.com',
    storageBucket: 'manage-user-1477b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ci8H7ytNNCIK58_1bn-0JZTORII9Q_c',
    appId: '1:728200174850:android:149d5c4702fdc63a92f61b',
    messagingSenderId: '728200174850',
    projectId: 'manage-user-1477b',
    storageBucket: 'manage-user-1477b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdF-NpiMrWrvcZ8Gz3NnOFQp1NrtI4eLs',
    appId: '1:728200174850:ios:338defe080e7dbef92f61b',
    messagingSenderId: '728200174850',
    projectId: 'manage-user-1477b',
    storageBucket: 'manage-user-1477b.appspot.com',
    iosClientId: '728200174850-0v59512fj99vmf2o0v38cq2gc0lm79il.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdF-NpiMrWrvcZ8Gz3NnOFQp1NrtI4eLs',
    appId: '1:728200174850:ios:0d6703cc1dfb3f2992f61b',
    messagingSenderId: '728200174850',
    projectId: 'manage-user-1477b',
    storageBucket: 'manage-user-1477b.appspot.com',
    iosClientId: '728200174850-i4bqun9vrut20ubsl3i58j8okhsnkdbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageuser.RunnerTests',
  );
}
